id: PDFB323D0
initial_creation_type: input
source_metadata:
  title: Kun spangs Chos grags dpals (fl. 14th cent.) Sems grel skor gsum lineage
    history
  author: ཀུན་སྤངས་ཆོས་གྲགས་དཔལ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-10-19);
    head entries and linebreaks encoded, no folio numbers, revision in process, no
    thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - 'Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was digitally published by བེ་རི་རིག་པའི་རྡོ་རྗེ།
    (ed.), Tashi Choeling Buddhist Center (Charlottesville, VA); སེམས་འགྲེལ་བླ་བརྒྱུད།

    (Digital Text version/id: ངེས་དོན་སྒྲོན་མེ། ༣༠, uploaded 25 /09/ 2013). (src)'
  - Text input:ནང་བསྟན་རིག་མཛོད་ངེས་དོན་དཔེ་ཚོགས་འཕྲུལ་དེབ་ལྟེ་གནས།, Tashi Choeling
    Buddhist Center (eds)
  - Editorial process:ནང་བསྟན་རིག་མཛོད་ངེས་དོན་དཔེ་ཚོགས་འཕྲུལ་དེབ་ལྟེ་གནས། (ntrd),
    Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/5049
  bases:
    cdc9:
      title: Kun spangs Chos grags dpals (fl. 14th cent.) Sems grel skor gsum lineage
        history
      order: 1
      base_file: cdc9.txt
created_at: '2022-04-15T18:33:22.573256'
last_modified_at: '2022-04-15T18:33:22.573263'
quality: null
